//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SCG.SyncBCCR.BL.cl.bcentral.si3 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SieteWSSoap", Namespace="http://bancocentral.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(abstractBaseObject))]
    public partial class SieteWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SearchSeriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSeriesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SieteWS() {
            this.Url = global::SCG.SyncBCCR.BL.Properties.Settings.Default.SCG_SyncBCCR_BL_cl_bcentral_si3_SieteWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SearchSeriesCompletedEventHandler SearchSeriesCompleted;
        
        /// <remarks/>
        public event GetSeriesCompletedEventHandler GetSeriesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bancocentral.org/SearchSeries", RequestNamespace="http://bancocentral.org/", ResponseNamespace="http://bancocentral.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Respuesta SearchSeries(string user, string password, string frequencyCode) {
            object[] results = this.Invoke("SearchSeries", new object[] {
                        user,
                        password,
                        frequencyCode});
            return ((Respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void SearchSeriesAsync(string user, string password, string frequencyCode) {
            this.SearchSeriesAsync(user, password, frequencyCode, null);
        }
        
        /// <remarks/>
        public void SearchSeriesAsync(string user, string password, string frequencyCode, object userState) {
            if ((this.SearchSeriesOperationCompleted == null)) {
                this.SearchSeriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchSeriesOperationCompleted);
            }
            this.InvokeAsync("SearchSeries", new object[] {
                        user,
                        password,
                        frequencyCode}, this.SearchSeriesOperationCompleted, userState);
        }
        
        private void OnSearchSeriesOperationCompleted(object arg) {
            if ((this.SearchSeriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchSeriesCompleted(this, new SearchSeriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://bancocentral.org/GetSeries", RequestNamespace="http://bancocentral.org/", ResponseNamespace="http://bancocentral.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Respuesta GetSeries(string user, string password, string firstDate, string lastDate, string[] seriesIds) {
            object[] results = this.Invoke("GetSeries", new object[] {
                        user,
                        password,
                        firstDate,
                        lastDate,
                        seriesIds});
            return ((Respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void GetSeriesAsync(string user, string password, string firstDate, string lastDate, string[] seriesIds) {
            this.GetSeriesAsync(user, password, firstDate, lastDate, seriesIds, null);
        }
        
        /// <remarks/>
        public void GetSeriesAsync(string user, string password, string firstDate, string lastDate, string[] seriesIds, object userState) {
            if ((this.GetSeriesOperationCompleted == null)) {
                this.GetSeriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSeriesOperationCompleted);
            }
            this.InvokeAsync("GetSeries", new object[] {
                        user,
                        password,
                        firstDate,
                        lastDate,
                        seriesIds}, this.GetSeriesOperationCompleted, userState);
        }
        
        private void OnGetSeriesOperationCompleted(object arg) {
            if ((this.GetSeriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSeriesCompleted(this, new GetSeriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bancocentral.org/")]
    public partial class Respuesta {
        
        private int codigoField;
        
        private string descripcionField;
        
        private fameSeries[] seriesField;
        
        private internetSeriesInfo[] seriesInfosField;
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public fameSeries[] Series {
            get {
                return this.seriesField;
            }
            set {
                this.seriesField = value;
            }
        }
        
        /// <remarks/>
        public internetSeriesInfo[] SeriesInfos {
            get {
                return this.seriesInfosField;
            }
            set {
                this.seriesInfosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.service.sdmx.sdms.sungard.com/")]
    public partial class fameSeries : fameNode {
        
        private seriesKey seriesKeyField;
        
        private int precisionField;
        
        private obs[] obsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public seriesKey seriesKey {
            get {
                return this.seriesKeyField;
            }
            set {
                this.seriesKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int precision {
            get {
                return this.precisionField;
            }
            set {
                this.precisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("obs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public obs[] obs {
            get {
                return this.obsField;
            }
            set {
                this.obsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.service.sdmx.sdms.sungard.com/")]
    public partial class seriesKey {
        
        private string keyFamilyIdField;
        
        private System.DateTime lastModifiedField;
        
        private bool lastModifiedFieldSpecified;
        
        private string lastModifiedUserField;
        
        private string seriesIdField;
        
        private string dataStageField;
        
        private bool existsField;
        
        private string descriptionField;
        
        private string descripIngField;
        
        private string descripEspField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string keyFamilyId {
            get {
                return this.keyFamilyIdField;
            }
            set {
                this.keyFamilyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime lastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastModifiedSpecified {
            get {
                return this.lastModifiedFieldSpecified;
            }
            set {
                this.lastModifiedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lastModifiedUser {
            get {
                return this.lastModifiedUserField;
            }
            set {
                this.lastModifiedUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string seriesId {
            get {
                return this.seriesIdField;
            }
            set {
                this.seriesIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dataStage {
            get {
                return this.dataStageField;
            }
            set {
                this.dataStageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool exists {
            get {
                return this.existsField;
            }
            set {
                this.existsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripIng {
            get {
                return this.descripIngField;
            }
            set {
                this.descripIngField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripEsp {
            get {
                return this.descripEspField;
            }
            set {
                this.descripEspField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.service.sdmx.sdms.sungard.com/")]
    public partial class internetSeriesInfo {
        
        private string seriesIdField;
        
        private frequency frequencyField;
        
        private bool frequencyFieldSpecified;
        
        private string frequencyCodeField;
        
        private observed observedField;
        
        private bool observedFieldSpecified;
        
        private string observedCodeField;
        
        private string spanishTitleField;
        
        private string englishTitleField;
        
        private string firstObservationField;
        
        private string lastObservationField;
        
        private string updatedAtField;
        
        private string createdAtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string seriesId {
            get {
                return this.seriesIdField;
            }
            set {
                this.seriesIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public frequency frequency {
            get {
                return this.frequencyField;
            }
            set {
                this.frequencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool frequencySpecified {
            get {
                return this.frequencyFieldSpecified;
            }
            set {
                this.frequencyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string frequencyCode {
            get {
                return this.frequencyCodeField;
            }
            set {
                this.frequencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public observed observed {
            get {
                return this.observedField;
            }
            set {
                this.observedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool observedSpecified {
            get {
                return this.observedFieldSpecified;
            }
            set {
                this.observedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string observedCode {
            get {
                return this.observedCodeField;
            }
            set {
                this.observedCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string spanishTitle {
            get {
                return this.spanishTitleField;
            }
            set {
                this.spanishTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string englishTitle {
            get {
                return this.englishTitleField;
            }
            set {
                this.englishTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string firstObservation {
            get {
                return this.firstObservationField;
            }
            set {
                this.firstObservationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lastObservation {
            get {
                return this.lastObservationField;
            }
            set {
                this.lastObservationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string updatedAt {
            get {
                return this.updatedAtField;
            }
            set {
                this.updatedAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string createdAt {
            get {
                return this.createdAtField;
            }
            set {
                this.createdAtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.service.sdmx.sdms.sungard.com/")]
    public enum frequency {
        
        /// <remarks/>
        UNDEFINED,
        
        /// <remarks/>
        SEMIANNUAL,
        
        /// <remarks/>
        WEEKLY,
        
        /// <remarks/>
        QUARTERLY,
        
        /// <remarks/>
        MONTHLY,
        
        /// <remarks/>
        ANNUAL,
        
        /// <remarks/>
        DAILY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.service.sdmx.sdms.sungard.com/")]
    public enum observed {
        
        /// <remarks/>
        UNDEFINED,
        
        /// <remarks/>
        SUMMED,
        
        /// <remarks/>
        LOW,
        
        /// <remarks/>
        HIGH,
        
        /// <remarks/>
        END,
        
        /// <remarks/>
        BEGINNING,
        
        /// <remarks/>
        AVERAGED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.service.sdmx.sdms.sungard.com/")]
    public partial class obs {
        
        private string indexDateStringField;
        
        private seriesKey seriesKeyField;
        
        private string statusCodeField;
        
        private double valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string indexDateString {
            get {
                return this.indexDateStringField;
            }
            set {
                this.indexDateStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public seriesKey seriesKey {
            get {
                return this.seriesKeyField;
            }
            set {
                this.seriesKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(fameNode))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(fameSeries))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.service.sdmx.sdms.sungard.com/")]
    public abstract partial class abstractBaseObject {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(fameSeries))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://web.service.sdmx.sdms.sungard.com/")]
    public partial class fameNode : abstractBaseObject {
        
        private string nodeLevelField;
        
        private string groupDimensionField;
        
        private string headerField;
        
        private string rootField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nodeLevel {
            get {
                return this.nodeLevelField;
            }
            set {
                this.nodeLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string groupDimension {
            get {
                return this.groupDimensionField;
            }
            set {
                this.groupDimensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string root {
            get {
                return this.rootField;
            }
            set {
                this.rootField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SearchSeriesCompletedEventHandler(object sender, SearchSeriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchSeriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchSeriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Respuesta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetSeriesCompletedEventHandler(object sender, GetSeriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSeriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSeriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Respuesta)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591